apiVersion: apps/v1
kind: Deployment
metadata:
  name: soar-remediation
  namespace: soar-system
  labels:
    app: soar-remediation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soar-remediation
  template:
    metadata:
      labels:
        app: soar-remediation
    spec:
      containers:
      - name: soar-remediation
        image: 920120424621.dkr.ecr.eu-central-1.amazonaws.com/casestudy2/dev/soar-remediation:latest
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: AWS_REGION
          value: "eu-central-1"
        - name: SQS_QUEUE_URL
          value: "https://sqs.eu-central-1.amazonaws.com/920120424621/casestudy2-dev-remediation-queue"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: soar-remediation
  namespace: soar-system
  labels:
    app: soar-remediation
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: metrics
  selector:
    app: soar-remediation
