---
- name: Deploy Lambda Functions
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "eu-central-1"
    
  tasks:
    - name: Package Lambda functions
      shell: |
        cd ../lambda/{{ item }}
        pip install -r requirements.txt -t .
        zip -r {{ item }}.zip .
      loop:
        - parser
        - engine
        - notify
        - remediate
      
    - name: Upload Lambda packages to S3
      command: >
        aws s3 cp ../lambda/{{ item }}/{{ item }}.zip 
        s3://casestudy2-lambda-packages/{{ item }}.zip
      loop:
        - parser
        - engine
        - notify
        - remediate
      
    - name: Update Lambda functions
      command: >
        aws lambda update-function-code 
        --function-name casestudy2-dev-{{ item }} 
        --s3-bucket casestudy2-lambda-packages 
        --s3-key {{ item }}.zip 
        --region {{ aws_region }}
      loop:
        - parser
        - engine
        - notify
        - remediate
      ignore_errors: yes
